#!/bin/bash
#
# ----------------------------------------------------------------------------------------------------
#
# Copyright (c) 2007, 2011, Oracle and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
#
# ----------------------------------------------------------------------------------------------------

dir=`/bin/pwd`

# Resolve location of this script so that mx.py can be found in the same directory
source="${BASH_SOURCE[0]}"
while [ -h "$source" ] ; do
  prev_source="$source"
  source="$(readlink "$source")";
  if [[ "$source" != /* ]]; then
    # if the link was relative, it was relative to where it came from
    dir="$( cd -P "$( dirname "$prev_source" )" && pwd )"
    source="$dir/$source"
  fi
done
dir="$( cd -P "$( dirname "$source" )" && pwd )"

if [ ! -f "$dir/mx.py" ]; then
    echo "Cannot find mx.py in $dir"
    exit 1
fi

# Prefer the interpreter specified by MX_PYTHON
if [ -n "${MX_PYTHON}" ]; then
    python_exe=${MX_PYTHON}
elif [ -n "${MX_PYTHON_VERSION}" ]; then
    python_exe=python${MX_PYTHON_VERSION}
else
    # Not all systems (e.g. Mac OS X) have 'python2' on the path.
    type python2.7 >/dev/null 2>&1
    if [ $? -eq 0 ]; then
        python_exe=python2.7
    else
        type python2 > /dev/null 2>&1
        if [ $? -eq 0 ]; then
            python_exe=python2
        else
            type python > /dev/null 2>&1
            if [ $? -eq 0 ]; then
                python_exe=python
            else
                type python3 > /dev/null 2>&1
                if [ $? -eq 0 ]; then
                    python_exe=python3
                else
                    echo "Cannot find Python on PATH"
                    exit 1
                fi
            fi
        fi
    fi
fi

type ${python_exe} >/dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "Cannot find ${python_exe} on PATH"
    exit 1
fi

exec $python_exe -u "$dir/mx.py" "$@"
